help:
    @grep '####' Makefile | grep -v grep | sed -e 's/####//'

cart: #### Setup Cart Component
    @bash component/cart.sh

user: #### Setup User Component
    @bash components/user.sh

shipping: #### Setup Shipping Component
    @bash components/shipping.sh

payment: #### Setup Payment Component
    @bash components/payment.sh

frontend: #### Setup Frontend Component
    @bash components/frontend.sh

mysql: #### Setup Mysql Component
    @bash components/mysql.sh

redis: #### Setup Redis Component
    @bash components/redis.sh

rabbitmq: #### Setup Rabbitmq Component
    @bash components/rabbitmq.sh

mongodb: #### Setup Mongodb Component
    @bash components/mongodb.sh

redis: #### Setup Redis Component
    @bash components/redis.sh
